name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update_db_docs:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'gradle'

      - run: |
          ./gradlew help "-Dorg.gradle.jvmargs=-Xmx2m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heapdump.hprof"

      - name: Store Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: heap-dump
          path: /tmp/heapdump.hprof
